### ISSUE TITLE
PDB fails to render

### ISSUE THREAD

**Issue by ning-y** [ning-y/Palantir#31]
## Why doesn't the Google Play Store version of Palantir work?

For better security, Google recently introduced additional restrictions on what Android applications can do. One of these restrictions interferes with how Palantir handles 3D models.

<details><summary>More details</summary><ul><br>
<li><b>Palantir versions v1.0.2 and below will no longer work</b> because <a href="https://github.com/ning-y/jPdbApi/issues/4">the RCSB APIs which it relies on has been deprecated</a>.</li>
<li>Palantir versions v1.0.3 and v1.0.4 replaces deprecated RCSB API calls with new ones, but this version was forced to set <code>targetSdkVersion 29</code>. (Since 2020/11/02, updates to Android applications on the Google Play Store <a href="https://web.archive.org/web/20201229045058/https%3A%2F%2Fsupport.google.com%2Fgoogleplay%2Fandroid-developer%2Fanswer%2F9859152%3Fvisit_id%3D637448141310657571-3265639120%26rd%3D1">must specify <code>targetSdkVersion >= 29</code></a>.)</li>
<li>Because <code>targetSdkVersion >= 29</code> disallows the execution of application data files (which is where the pre-compiled VMD binary used to render PDBs are saved, <b>Palantir version v1.0.3 does not work either</b> because it is unable to render PDBs at all. See the <a href="https://issuetracker.google.com/issues/128554619">Google issue tracker</a> or <a href="https://stackoverflow.com/a/60653812/6910451">StackExchange</a> threads.</li>
</ul></details>

## Can I get a version of Palantir that works?

Yes. Download the v1.0.5 signed APK (coming soon) from the releases page.

<details><summary>More details</summary><ul><br>
<li>Palantir v1.0.5 reverts <code>targetSdkVersion 29</code> to <code>targetSdkVersion 28</code>, while using up-to-date RCSB API calls. However, I could not upload this version to the Google Play Store since they strictly require <code>targetSdkVersion 29</code> (see above).</li>
</ul></details>

## What would it take to get a working version of Palantir unto the Google Play Store?

I think that I (we?) would need to bring in the relevant parts of the VMD source code via the NDK properly, as opposed to right now where VMD is pre-compiled as a whole and shipped as a big binary executable.

Unfortunately, I have other projects going on right now, so I cannot spare the time to learn and make these changes.

<div align="center">
<img src="https://user-images.githubusercontent.com/22320312/103260159-a2058880-49d7-11eb-8cb5-53c10f17b11f.png">
</div><br>

If you are comfortable giving it a go, please do! I pinky promise to review your PRs ASAP.

**Comment by ning-y** [comment]
<details><summary>Screenshot:</summary>
<div align="center">
<img src="https://user-images.githubusercontent.com/22320312/103253474-5b566500-49bc-11eb-9a27-2cfab13c2cfb.png">
</div>
</details>

```
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err: java.io.IOException: Cannot run program "/data/user/0/io.ningyuan.palantir/files/vmd/vmd": error=13, Permission denied
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at io.ningyuan.palantir.utils.PdbRenderer.runVmd(PdbRenderer.java:108)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at io.ningyuan.palantir.utils.PdbRenderer.pdbFileToObjFile(PdbRenderer.java:64)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at io.ningyuan.palantir.utils.PdbRenderer.doInBackground(PdbRenderer.java:199)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at io.ningyuan.palantir.utils.PdbRenderer.doInBackground(PdbRenderer.java:30)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.lang.Thread.run(Thread.java:923)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err: Caused by: java.io.IOException: error=13, Permission denied
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.lang.UNIXProcess.forkAndExec(Native Method)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.lang.ProcessImpl.start(ProcessImpl.java:141)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err:     at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
2020-12-29 09:56:57.660 io.ningyuan.palantir W/System.err: 	... 10 more
```

**Comment by ning-y** [comment]
targetSdkVersion >= 29 intentionally blocks the execution of application data files.

- Google issue tracker: https://issuetracker.google.com/issues/128554619
- Stackexchange thread: https://stackoverflow.com/a/60653812/6910451
